" plugin

call plug#begin('~/.vim/plug')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'flazz/vim-colorschemes'
Plug 'airblade/vim-gitgutter'
Plug 'preservim/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'
Plug 'vim-jp/vimdoc-ja'
call plug#end()

" config

"" file
set autoread
set fenc=utf-8
set fileencodings=ucs-boms,utf-8,euc-jp,cp932
set fileformats=unix,dos,mac
set nofixeol
set noswapfile
set hidden
set nobackup
set nobomb

"" interface
set cursorline
set display+=lastline
set laststatus=2
set list
set listchars=eol:↲,extends:»,nbsp:%,precedes:«,space:·,tab:»-
set mouse=a
set number
set shell=zsh
set showcmd
set showmatch
set virtualedit=onemore
set wildmode=list:longest
set wrap

"" search
set hlsearch
set ignorecase
set incsearch
set smartcase
set wrapscan

"" tab
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set softtabstop=4
set tabstop=4

"" syntastic
syntax on
colorscheme molokai_dark
hi Normal guibg=NONE ctermbg=NONE

"" clipboard
set clipboard=unnamedplus

""" wsl
if executable('copy')
    let s:clip='copy'
    au TextYankPost * call system('echo '.shellescape(join(v:event.regcontents, "\<CR>")).' | '.s:clip)
endif

""" termux
if executable('termux-clipboard-set')
    au TextYankPost * call system('termux-clipboard-set &', @")
    function Paste(p)
        let sysclip=system('termux-clipboard-get')
        if sysclip != @"
            let @"=sysclip
        endif
        return a:p
    endfunction
    noremap <expr> p Paste('p')
    noremap <expr> P Paste('P')
endif


"" vim-plug
let g:plug_window = 'topleft'

"" vim-airline
let g:airline_theme = 'luna'
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline#extensions#virtualenv#enabled = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.paste = '∥'
let g:airline_symbols.linenr = '¶'
let g:airline#extensions#branch#prefix     = '⎇'
let g:airline#extensions#linecolumn#prefix = '¶'
let g:airline#extensions#paste#symbol      = '∥'
let g:airline#extensions#readonly#symbol   = '⊘'
if !exists('g:airline_powerline_fonts')
    let g:airline_left_alt_sep = ''
    let g:airline_left_sep = ''
    let g:airline_right_alt_sep = ''
    let g:airline_right_sep = ''
    let g:airline_symbols.branch = ''
    let g:airline_symbols.readonly = ''
    let g:airline#extensions#tabline#left_alt_sep = ''
    let g:airline#extensions#tabline#left_sep = ''
else
    let g:airline_left_sep = '»'
    let g:airline_left_sep = '▶'
    let g:airline_right_sep = '«'
    let g:airline_right_sep = '◀'
    let g:airline_symbols.branch = '⎇'
endif

"" vim-gitgutter
set updatetime=100

" keymap

noremap <down> gj
noremap <up> gk
nnoremap <Esc><Esc> :nohlsearch<CR><Esc>
noremap <S-e> :NERDTreeToggle<CR>
