[packages.linux.pacman]
packages = [
  "git",
  "helix",
  "zsh",
  "git-credential-oauth",
  "ripgrep",
  "git-delta",
  "eza",
  # "teip",
  "jq",
  "fzf",
  "bat",
  "fd",
  "hexyl",
  "ghq",
]

[packages.linux.homebrew]
taps = []
brews = [
  "git",
  "helix",
  "zsh",
  "git-credential-libsecret",
  "git-credential-oauth",
  "ripgrep",
  "git-delta",
  "eza",
  "teip",
  "jq",
  "fzf",
  "bat",
  "fd",
  "hexyl",
  "ghq",
]
