# Run commands before zshrc at login.

## Paths
### Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

### Set the list of directories that Zsh searches for programs.
path=(
  "${HOME}/.local/bin"
  ${path}
)
