# Run commands before zshrc at login.

## load environment.d on non-desktop environment.
if [[ "${DOTFILES_ENV_LOADED}" != "true" ]]; then
  {{- with $envs := ( cat
    (includeTemplate "config/environment.d/xdg-user-dir/init.conf")
    (includeTemplate "config/environment.d/xdg-base-dirs/init.conf")
    (includeTemplate "config/environment.d/editor.conf")
    (includeTemplate "config/environment.d/gpg-socket.conf")
    (includeTemplate "config/environment.d/dotfiles-env-loaded.conf")
  )}}
  {{- $envs
    | replaceAllRegex "\n" "\n\n"
    | replaceAllRegex "(^|\n) *#+.*?\n" ""
    | replaceAllRegex "\n+" "\n"
    | replaceAllRegex "\n(.+=)" "\n  export $1"
  }}
  {{- end}}
fi

## Paths
### Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

### Set the list of directories that Zsh searches for programs.
path=(
  "${HOME}/.local/bin"
  ${path}
)
