# Define environment variables.

## load environment.d on non-desktop environment.
if [[ "${DOTFILES_ENV_LOADED}" != "true" ]]; then
  {{- with $envs := ( cat
    (includeTemplate "config/environment.d/xdg-user-dir/init.conf")
    (includeTemplate "config/environment.d/xdg-base-dirs/init.conf")
    (includeTemplate "config/environment.d/editor.conf")
    (includeTemplate "config/environment.d/gpg-socket.conf")
    (includeTemplate "config/environment.d/dotfiles-env-loaded.conf")
  )}}
  {{- $envs
    | replaceAllRegex "\n" "\n\n"
    | replaceAllRegex "(^|\n) *#+.*?\n" ""
    | replaceAllRegex "\n+" "\n"
    | replaceAllRegex "\n(.+=)" "\n  export $1"
  }}
  {{- end}}
fi

## dotfiles path
export DOTFILES_DIR="${HOME}/.dotfiles"

## zsh config path
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
