[".local/share/zsh/zinit/zinit.git"]
type = "git-repo"
url = "https://github.com/zdharma-continuum/zinit"

[".local/share/nvim/site/pack/packer/opt/packer.nvim"]
type = "git-repo"
url = "https://github.com/wbthomason/packer.nvim"
