# Run commands before zshrc at login.

## Load environment.d
source "${XDG_CONFIG_HOME}/environment.d/xdg-base-dir.conf"
source "${XDG_CONFIG_HOME}/environment.d/envvars.conf"

## Paths
### Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

### Set the list of directories that Zsh searches for programs.
path=(
    "${XDG_BINARY_HOME}"
    /usr/local/{bin,sbin}
    ${path}
)
